from typing import List, Optional
from pydantic import BaseModel, Field
from src.models.EmbeddedLinkModel import EmbeddedLinkModel
from src.models.SeoMetadataModel import SeoMetadataModel


class ArticleModel(BaseModel):
    # An article must have a title and content.
    # If these can't be extracted, the node should fail.
    title: str
    content: str

    top_image: Optional[str] = None

    # Summary is generated by the LLM, so it starts as None.
    summary: Optional[str] = None
    reading_time: Optional[int] = Field(None, description="Estimated reading time in minutes (English)")

    # These are extracted by newspaper3k or the LLM.
    published_date: Optional[str] = None
    author: Optional[str] = None # Note: author can also be List[str]

    # categorization
    category: List[str] = Field(
        default_factory=list,
        description="A list of up to 3 main categories."
    )

    countries: List[str] = Field(
        default_factory=list,
        description="A list of countries relevant to the article."
    )

    category_ids: List[str] = Field(
        default_factory=list,
        description="The corresponding external IDs for the categories."
    )

    # Use default_factory to ensure this is always a list,
    # which is easier to append to than an Optional.
    embedded_links: List[EmbeddedLinkModel] = Field(default_factory=list)

    # SEO Data
    seo: Optional[SeoMetadataModel] = None

    # Translation Data
    title_ar: Optional[str] = None
    summary_ar: Optional[str] = None
    content_ar: Optional[str] = None
    reading_time_ar: Optional[str] = Field(None, description="Estimated reading time in minutes (Arabic numerals)")