from typing import List, Optional
from pydantic import BaseModel, Field
from src.models.EmbeddedLinkModel import EmbeddedLinkModel

class ArticleModel(BaseModel):
    # An article must have a title and content.
    # If these can't be extracted, the node should fail.
    title: str
    content: str

    # Summary is generated by the LLM, so it starts as None.
    summary: Optional[str] = None

    # These are extracted by newspaper3k or the LLM.
    published_date: Optional[str] = None
    author: Optional[str] = None # Note: author can also be List[str]

    # These are populated by later nodes.
    category: Optional[str] = None
    sub_category: Optional[str] = None

    # Use default_factory to ensure this is always a list,
    # which is easier to append to than an Optional.
    embedded_links: List[EmbeddedLinkModel] = Field(default_factory=list)