from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class SeoMetadataModel(BaseModel):
    """
    Structured output for the SEO Node.
    """
    # 1. The Core SEO Fields generated by LLM
    meta_title: str = Field(..., description="SEO optimized title, max 60 chars")
    meta_description: str = Field(..., description="SEO optimized description, max 160 chars")
    slug: str = Field(..., description="URL-friendly slug")
    primary_keywords: List[str] = Field(..., description="3-5 focus keywords")

    # 2. Social Meta Tags
    og_title: str = Field(..., description="Open Graph Title")
    og_description: str = Field(..., description="Open Graph Description")
    twitter_card_title: str = Field(..., description="Twitter Card Title")
    twitter_card_description: str = Field(..., description="Twitter Card Description")

    # 3. The Full JSON-LD Script (Constructed in code, or by LLM)
    # We will store it as a dict here, and the API/Webhook can serialize it to a string/script tag.
    json_ld_schema: Dict[str, Any] = Field(default_factory=dict)